#!/usr/bin/env python3
"""Regenerate the A/B comparison table in orfs/README.md.

Invoked by `bazelisk run //:update-a-b`. The job's `data` deps build the two
AES flows first (GT2N and ASAP7), each through detailed route to finish. This
script reads the per-stage ORFS metrics JSONs each flow emits under
bazel-out/.../orfs/logs/<platform>/<DESIGN>/base/*.json and the resolved
arguments under bazel-out/.../orfs/results/<platform>/<DESIGN>/base/*.args.json,
then renders:

  * the minimum achievable clock period at each stage, in picoseconds, derived
    from the stage's reported Fmax (min_period_ps = 1e12 / fmax_hz),
  * the placement-density and core-utilization knobs and the achieved
    utilization, and
  * the cell and die area.

The table is spliced into orfs/README.md between the A/B markers. Paths are
resolved via $BUILD_WORKSPACE_DIRECTORY (set by `bazel run`).
"""

import glob
import json
import os
import sys

START = "<!-- A/B:START -->"
END = "<!-- A/B:END -->"

# Plot rendered alongside the table (regenerated by //:update-a-b).
PLOT = "ab_clock_period.png"

# Flow stages in order, paired with their ORFS metric-key prefix. "Detailed
# route" maps to the finish stage (post-route timing/area).
STAGES = [
    ("Floorplan", "floorplan"),
    ("Placement", "detailedplace"),
    ("CTS", "cts"),
    ("Global route", "globalroute"),
    ("Detailed route", "finish"),
]

# The A/B design (AES-128). ORFS keys results/logs dirs by DESIGN_NAME, which
# bazel-orfs takes from the flow's `top` — i.e. aes_cipher_top, not "aes".
DESIGN = "aes_cipher_top"

# Per platform, the last stage that ran (used for area / achieved-util rows).
# Both reach finish now that the bumped OpenROAD routes GT2N's backside stack.
LAST_STAGE = {"gt2n": "finish", "asap7": "finish"}

CLOCK = "core_clock"


def workspace():
    return os.environ.get("BUILD_WORKSPACE_DIRECTORY", os.getcwd())


def _merge_json(pattern):
    merged = {}
    for path in glob.glob(pattern, recursive=True):
        try:
            with open(path, encoding="utf-8") as fh:
                data = json.load(fh)
        except (ValueError, OSError):
            continue
        if isinstance(data, dict):
            merged.update(data)
    return merged


def load_metrics(platform):
    """Merge every per-stage metrics JSON for <platform>/<DESIGN> into one dict."""
    base = os.path.join(workspace(), "bazel-out", "*", "bin", "orfs")
    return _merge_json(os.path.join(base, "logs", platform, DESIGN, "base", "*.json"))


def load_args(platform):
    """Merge the resolved per-stage argument JSONs (CORE_UTILIZATION, etc.)."""
    base = os.path.join(workspace(), "bazel-out", "*", "bin", "orfs")
    return _merge_json(
        os.path.join(base, "results", platform, DESIGN, "base", "*.args.json")
    )


def min_period_ps(metrics, prefix):
    """Minimum clock period (ps) from the stage's Fmax, or None."""
    for key in (
        "{}__timing__fmax__clock:{}".format(prefix, CLOCK),
        "{}__timing__fmax".format(prefix),
    ):
        fmax = metrics.get(key)
        if isinstance(fmax, (int, float)) and fmax > 0:
            return 1e12 / fmax
    return None


def area(metrics, platform, kind):
    val = metrics.get("{}__design__{}__area".format(LAST_STAGE[platform], kind))
    return val if isinstance(val, (int, float)) else None


def utilization(metrics, platform):
    val = metrics.get("{}__design__instance__utilization".format(LAST_STAGE[platform]))
    return val if isinstance(val, (int, float)) else None


def num(args, key):
    try:
        return float(args[key])
    except (KeyError, TypeError, ValueError):
        return None


def cell(value, fmt="{:.3f}", skipped=False):
    if skipped:
        return "_skipped_"
    if value is None:
        return "n/a"
    return fmt.format(value)


def render(gt2n_m, asap7_m, gt2n_a, asap7_a):
    rows = ["| Metric | GT2N (2nm) | ASAP7 (7nm) |", "| --- | --- | --- |"]
    for label, prefix in STAGES:
        g = min_period_ps(gt2n_m, prefix)
        a = min_period_ps(asap7_m, prefix)
        rows.append(
            "| Min clock period — {} (ps) | {} | {} |".format(
                label, cell(g, "{:.1f}"), cell(a, "{:.1f}")
            )
        )
    rows.append(
        "| Core utilization target (%) | {} | {} |".format(
            cell(num(gt2n_a, "CORE_UTILIZATION"), "{:.0f}"),
            cell(num(asap7_a, "CORE_UTILIZATION"), "{:.0f}"),
        )
    )
    rows.append(
        "| Placement density target | {} | {} |".format(
            cell(num(gt2n_a, "PLACE_DENSITY"), "{:.2f}"),
            cell(num(asap7_a, "PLACE_DENSITY"), "{:.2f}"),
        )
    )
    rows.append(
        "| Achieved utilization | {} | {} |".format(
            cell(utilization(gt2n_m, "gt2n")), cell(utilization(asap7_m, "asap7"))
        )
    )
    rows.append(
        "| Cell area (um^2) | {} | {} |".format(
            cell(area(gt2n_m, "gt2n", "instance")),
            cell(area(asap7_m, "asap7", "instance")),
        )
    )
    rows.append(
        "| Die area (um^2) | {} | {} |".format(
            cell(area(gt2n_m, "gt2n", "die")), cell(area(asap7_m, "asap7", "die"))
        )
    )

    return "\n".join(
        [
            START,
            "",
            "Minimum clock period is derived from each stage's reported Fmax "
            "(`1e12 / fmax`, in ps); it grows through the flow as real "
            "parasitics land. Both PDKs run the same `aes` (AES-128) RTL all the way "
            "through detailed route to a final GDS.",
            "",
            "\n".join(rows),
            "",
            "_Same `aes` RTL through both PDKs. Regenerate with "
            "`bazelisk run //:update-a-b`._",
            "",
            END,
        ]
    )


def _render_plot(gt2n_m, asap7_m, out_path):
    """In-process matplotlib render (raises if matplotlib is missing)."""
    import matplotlib

    matplotlib.use("Agg")  # headless: no display needed
    import matplotlib.pyplot as plt

    labels = [label for label, _ in STAGES]
    gt2n = [min_period_ps(gt2n_m, prefix) or 0.0 for _, prefix in STAGES]
    asap7 = [min_period_ps(asap7_m, prefix) or 0.0 for _, prefix in STAGES]

    xs = range(len(labels))
    width = 0.38
    fig, ax = plt.subplots(figsize=(8.0, 4.5))
    ax.bar([x - width / 2 for x in xs], gt2n, width, label="GT2N (2nm)")
    ax.bar([x + width / 2 for x in xs], asap7, width, label="ASAP7 (7nm)")
    ax.set_xticks(list(xs))
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylabel("Min clock period (ps) — lower is faster")
    ax.set_title("AES-128: min clock period through the flow")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)


def write_plot(gt2n_m, asap7_m, out_path):
    """Render the plot, best-effort.

    Tries in-process matplotlib first; under Bazel's hermetic interpreter that
    usually isn't present, so fall back to a host python3 that has matplotlib
    (re-invoking this file in --plot mode). Non-fatal: the table still updates
    if no matplotlib is found anywhere.
    """
    try:
        _render_plot(gt2n_m, asap7_m, out_path)
        print("Wrote plot {}".format(out_path))
        return True
    except Exception:  # noqa: BLE001 - in-process matplotlib not available
        pass

    import shutil
    import subprocess
    import tempfile

    candidates = ["/usr/bin/python3", "/usr/local/bin/python3", shutil.which("python3")]
    tmp = tempfile.mkdtemp()
    g_json = os.path.join(tmp, "gt2n.json")
    a_json = os.path.join(tmp, "asap7.json")
    json.dump(gt2n_m, open(g_json, "w"))
    json.dump(asap7_m, open(a_json, "w"))
    for py in candidates:
        if not py or not os.path.exists(py):
            continue
        if subprocess.run([py, "-c", "import matplotlib"], capture_output=True).returncode:
            continue
        try:
            subprocess.run(
                [py, os.path.abspath(__file__), "--plot", g_json, a_json, out_path],
                check=True,
            )
            print("Wrote plot {} (host matplotlib)".format(out_path))
            return True
        except subprocess.CalledProcessError:
            continue
    print("matplotlib unavailable (in-process and host), skipping plot")
    return False


def splice(readme_path, block):
    with open(readme_path, encoding="utf-8") as fh:
        text = fh.read()
    if START in text and END in text:
        text = text[: text.index(START)] + block + text[text.index(END) + len(END) :]
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(text)


def main():
    # Internal: `--plot <gt2n.json> <asap7.json> <out.png>` renders just the
    # plot (used by write_plot to re-invoke a host python3 that has matplotlib).
    if len(sys.argv) >= 5 and sys.argv[1] == "--plot":
        _, _, g_json, a_json, out = sys.argv[:5]
        _render_plot(
            json.load(open(g_json, encoding="utf-8")),
            json.load(open(a_json, encoding="utf-8")),
            out,
        )
        return

    gt2n_m, asap7_m = load_metrics("gt2n"), load_metrics("asap7")
    gt2n_a, asap7_a = load_args("gt2n"), load_args("asap7")
    if not gt2n_m or not asap7_m:
        sys.exit(
            "no metrics found — run via `bazelisk run //:update-a-b` so the "
            "flows build first (gt2n={}, asap7={} keys)".format(
                len(gt2n_m), len(asap7_m)
            )
        )
    orfs_dir = os.path.join(workspace(), "orfs")
    splice(
        os.path.join(orfs_dir, "README.md"), render(gt2n_m, asap7_m, gt2n_a, asap7_a)
    )
    print("Updated A/B table in {}".format(os.path.join(orfs_dir, "README.md")))
    write_plot(gt2n_m, asap7_m, os.path.join(orfs_dir, PLOT))


if __name__ == "__main__":
    main()
